### ISSUE TITLE
Clicking on "Close Window" closes modified project without asking for saving it

### ISSUE THREAD

**Issue by bkiefer** [bkiefer/GraVE#12]

**Comment by aWelker** [comment]
On closing, `EditorInstance` separately closes all opened `EditorProject` instances via the method `close(ProjectEditor editor, int DialogType)`.

This method checks whether there have been changes in the concerned instance, using `EditorProject.hasChanged()`.

`hasChanged()` compares the current hash code of the concerned Sceneflow instance to the hash code it had at the last save.

Currently, `hasChanged()` almost always returns false, because Sceneflow is a subclass of SuperNode which is a subclass of BasicNode whose `getHashCode()` method returns the hash code of the node Id, which is very unlikely to get changed.

**Comment by aWelker** [comment]
This should be solved by last commit to developer; hashCode() has been implemented/updated in all relevant classes.

**Comment by aWelker** [comment]
Reopening this issue until copy-paste is completely renewed. Might have to be adapted then, at least right now it seems to not properly recognize when a node has been added via copy-paste.
